/*
 * Copyright (C) 2026 — Generated by MenuBuilder AI, inspired by Steve Spano
 *                        (SteveSpano009@gmail.com)
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

/**
 * @file  main.c
 * @date  2026-02-27 12:00:00 -05:00
 * @brief Desktop test harness for the DAQ menu system.
 *
 * Provides two modes of operation:
 *   --demo   Runs a set of canned commands to exercise the parser, then exits.
 *   (none)   Interactive mode: reads lines from stdin until EXIT or EOF.
 *
 * This file is intended for development and validation on an x86 desktop.
 * Replace it with a UART/RTOS front-end when integrating into a target.
 */

/*
 * ===========================================================================
 *  REVISION HISTORY
 * ===========================================================================
 *  Rev    Date        Author                          Description
 * ---------------------------------------------------------------------------
 *  1.0    2026-02-27  MenuBuilder AI / Steve Spano    Initial generation
 * ===========================================================================
 */

#include "menu.h"

#include <stdio.h>
#include <string.h>
#include <ctype.h>

/**
 * @brief Case-insensitive string comparison used by main for argument parsing.
 *
 * Compares two NUL-terminated ASCII strings byte-by-byte, lowering each
 * character before comparison.
 *
 * @param a  Left-hand string.
 * @param b  Right-hand string.
 * @return 0 when equal ignoring case.
 */
static int main_stricmp(const char *a, const char *b)
{
    while (*a != '\0' && *b != '\0') {
        unsigned char ca = (unsigned char)tolower((unsigned char)*a);
        unsigned char cb = (unsigned char)tolower((unsigned char)*b);
        if (ca != cb) {
            return (int)ca - (int)cb;
        }
        ++a;
        ++b;
    }
    return (int)(unsigned char)tolower((unsigned char)*a)
         - (int)(unsigned char)tolower((unsigned char)*b);
}

/**
 * @brief Strips trailing newline and carriage-return characters in place.
 *
 * Scans backward from the end of the string, replacing '\\n' and '\\r'
 * with NUL until a non-line-ending character (or the start) is reached.
 *
 * @param s  Mutable NUL-terminated string to trim.
 */
static void strip_newline(char *s)
{
    size_t len = strlen(s);
    while (len > 0u && (s[len - 1u] == '\n' || s[len - 1u] == '\r')) {
        s[--len] = '\0';
    }
}

/**
 * @brief Runs a predefined set of demo commands to exercise the parser.
 *
 * Each command is printed before execution so the user can see what the
 * parser receives and what each callback produces.  Covers required
 * parameters, optional parameters, missing parameters, built-in help,
 * and unknown command handling.
 */
static void run_demo(void)
{
    static const char *demo_commands[] = {
        "HELP",
        "?",
        "daq init 1000 0xFF",
        "DAQ INIT 500",
        "daq start 5000",
        "daq start",
        "daq stop",
        "daq read 3",
        "daq set gain 2 12",
        "daq set trigger EXT 3300",
        "daq set trigger INT",
        "daq status",
        "daq status verbose",
        "daq calibrate 1 2500",
        "daq calibrate 0",
        "daq save config MyProfile",
        "daq load config MyProfile",
        "BOGUS COMMAND",
        "EXIT"
    };

    size_t count = sizeof(demo_commands) / sizeof(demo_commands[0]);
    size_t i;

    printf("=== MenuBuilder Demo Mode ===\n\n");

    for (i = 0; i < count; ++i) {
        printf("CMD> %s\n", demo_commands[i]);

        /* check for EXIT before dispatch */
        if (main_stricmp(demo_commands[i], "EXIT") == 0 ||
            main_stricmp(demo_commands[i], "QUIT") == 0) {
            printf("Exiting demo.\n");
            break;
        }

        Menu_ProcessLine(demo_commands[i]);
        printf("\n");
    }
}

/**
 * @brief Entry point for the DAQ menu test harness.
 *
 * Initializes the menu parser, checks for --demo on the command line,
 * and either runs the demo sequence or enters an interactive read-eval
 * loop.  The interactive loop terminates on EXIT, QUIT, or EOF.
 *
 * @param argc  Argument count from the OS.
 * @param argv  Argument vector from the OS.
 * @return 0 on clean exit.
 */
int main(int argc, char *argv[])
{
    char line[MENU_MAX_INPUT_LEN];

    Menu_Init();

    /* check for --demo flag */
    if (argc > 1 && strcmp(argv[1], "--demo") == 0) {
        run_demo();
        return 0;
    }

    printf("DAQ Menu Test Harness (type HELP or ? for commands, EXIT to quit)\n");

    while (1) {
        printf("CMD> ");
        fflush(stdout);

        if (fgets(line, (int)sizeof(line), stdin) == NULL) {
            printf("\nEOF received. Exiting.\n");
            break;
        }

        strip_newline(line);

        /* skip blank lines */
        if (line[0] == '\0') {
            continue;
        }

        /* built-in EXIT / QUIT */
        if (main_stricmp(line, "EXIT") == 0 ||
            main_stricmp(line, "QUIT") == 0) {
            printf("Goodbye.\n");
            break;
        }

        Menu_ProcessLine(line);
    }

    return 0;
}
