/*
 * Copyright (C) 2026 — Generated by MenuBuilder AI, inspired by Steve Spano
 *                        (SteveSpano009@gmail.com)
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

/**
 * @file  menu.h
 * @date  2026-02-27 12:00:00 -05:00
 * @brief Public API for the deterministic embedded command parser and dispatcher.
 *
 * Declares the command context structure, callback signature, command
 * definition table entry, and all public parser/dispatcher functions used
 * by the DAQ menu system.  Also forward-declares every DAQ callback so the
 * linker can resolve them from menu_callback_Test.c.
 */

#ifndef MENU_H
#define MENU_H

#include <stddef.h>

/** Maximum length of a raw input line (including NUL). */
#define MENU_MAX_INPUT_LEN 256

/** Maximum number of whitespace-delimited tokens per input line. */
#define MENU_MAX_TOKENS    16

/** Maximum number of parameter arguments passed to a callback. */
#define MENU_MAX_ARGS       8

/**
 * @brief Holds parsed parameter tokens that are forwarded to a callback.
 *
 * @c argv entries are borrowed pointers into the tokenized input buffer.
 * The caller must not free them or retain them beyond the callback scope.
 */
typedef struct MenuCommandContext {
    int          argc;                    /**< Number of parsed arguments.   */
    const char  *argv[MENU_MAX_ARGS];     /**< Argument value pointers.      */
} MenuCommandContext;

/**
 * @brief Callback signature for every registered command handler.
 *
 * @param ctx  Pointer to parsed arguments for the matched command.
 * @return 0 on success; negative values indicate command-specific errors.
 */
typedef int (*MenuCallback)(const MenuCommandContext *ctx);

/**
 * @brief Static command-table entry generated from FUNCTION:COMMAND:DESCRIPTION.
 */
typedef struct MenuCommandDef {
    const char   *function_name;  /**< C callback function name.           */
    const char   *syntax;         /**< Full command syntax string.         */
    const char   *description;    /**< Human-readable help text.           */
    MenuCallback  callback;       /**< Pointer to the handler function.    */
} MenuCommandDef;

/**
 * @brief Parses every command syntax string and builds runtime match tables.
 */
void Menu_Init(void);

/**
 * @brief Tokenizes one input line and dispatches it to the matching callback.
 *
 * @param line  Raw NUL-terminated user input.
 * @return Callback return code on match, 0 for help/empty, -1 for unknown.
 */
int Menu_ProcessLine(const char *line);

/**
 * @brief Prints all registered commands with aligned help text.
 */
void Menu_PrintHelp(void);

/**
 * @brief Returns the command definition table and its element count.
 *
 * @param count  Optional output pointer receiving the number of entries.
 * @return Pointer to the internal immutable command definition array.
 */
const MenuCommandDef *Menu_GetCommands(size_t *count);

/* ---- DAQ callback forward declarations --------------------------------- */

int DaqInit(const MenuCommandContext *ctx);
int DaqStart(const MenuCommandContext *ctx);
int DaqStop(const MenuCommandContext *ctx);
int DaqRead(const MenuCommandContext *ctx);
int DaqSetGain(const MenuCommandContext *ctx);
int DaqSetTrigger(const MenuCommandContext *ctx);
int DaqStatus(const MenuCommandContext *ctx);
int DaqCalibrate(const MenuCommandContext *ctx);
int DaqSaveConfig(const MenuCommandContext *ctx);
int DaqLoadConfig(const MenuCommandContext *ctx);

#endif /* MENU_H */
