/*
 * Copyright (C) 2026 — Generated by MenuBuilder AI, inspired by Steve Spano
 *                        (SteveSpano009@gmail.com)
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

/**
 * @file  menu.c
 * @date  2026-02-27 12:00:00 -05:00
 * @brief Deterministic parser and dispatcher for the DAQ command table.
 *
 * Implements tokenization, syntax parsing, case-insensitive keyword matching,
 * explicit match signaling, and aligned help output.  All command definitions
 * are generated from menu_commands_daq.txt.
 */

/*
 * ===========================================================================
 *  REVISION HISTORY
 * ===========================================================================
 *  Rev    Date        Author                          Description
 * ---------------------------------------------------------------------------
 *  1.0    2026-02-27  MenuBuilder AI / Steve Spano    Initial generation
 * ===========================================================================
 */

#include "menu.h"

#include <ctype.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>

/* ---- internal types ---------------------------------------------------- */

/** Classification of a single token within a command syntax string. */
typedef enum MenuTokenType {
    MENU_TOKEN_KEYWORD = 0,       /**< Literal keyword (e.g. DAQ, SET).    */
    MENU_TOKEN_REQUIRED_PARAM,    /**< Required parameter [NAME].          */
    MENU_TOKEN_OPTIONAL_PARAM     /**< Optional parameter {NAME}.          */
} MenuTokenType;

/** One parsed token from a syntax definition. */
typedef struct ParsedToken {
    MenuTokenType type;           /**< Token classification.               */
    char          text[32];       /**< Keyword text or parameter name.     */
} ParsedToken;

/** Pre-parsed metadata for one command used at dispatch time. */
typedef struct ParsedCommand {
    ParsedToken tokens[MENU_MAX_TOKENS]; /**< Parsed syntax tokens.        */
    int         token_count;             /**< Total tokens in syntax.       */
    int         min_tokens;              /**< Min input tokens for match.   */
    int         max_tokens;              /**< Max input tokens for match.   */
    int         valid;                   /**< 1 if syntax parsed cleanly.   */
} ParsedCommand;

/* ---- generated command table ------------------------------------------- */

static MenuCommandDef g_commands[] = {
    { "DaqInit",       "DAQ INIT [RATE_HZ] {CHANNEL_MASK}",        "Initialize acquisition rate and optional channel mask",  DaqInit       },
    { "DaqStart",      "DAQ START {DURATION_MS}",                  "Start acquisition, optionally for a fixed duration",     DaqStart      },
    { "DaqStop",       "DAQ STOP",                                 "Stop acquisition",                                       DaqStop       },
    { "DaqRead",       "DAQ READ [CHANNEL]",                       "Read latest sample for a channel",                       DaqRead       },
    { "DaqSetGain",    "DAQ SET GAIN [CHANNEL] [GAIN_DB]",         "Set channel gain in dB",                                 DaqSetGain    },
    { "DaqSetTrigger", "DAQ SET TRIGGER [SOURCE] {LEVEL}",         "Set trigger source and optional level",                  DaqSetTrigger },
    { "DaqStatus",     "DAQ STATUS {DETAIL}",                      "Show DAQ status",                                        DaqStatus     },
    { "DaqCalibrate",  "DAQ CALIBRATE [CHANNEL] {REFERENCE_MV}",   "Calibrate a channel with optional reference value",      DaqCalibrate  },
    { "DaqSaveConfig", "DAQ SAVE CONFIG [NAME]",                   "Save current configuration profile",                     DaqSaveConfig },
    { "DaqLoadConfig", "DAQ LOAD CONFIG [NAME]",                   "Load configuration profile",                             DaqLoadConfig }
};

/** Number of generated command entries. */
#define COMMAND_COUNT (sizeof(g_commands) / sizeof(g_commands[0]))

/** Pre-parsed metadata array, one entry per command. */
static ParsedCommand g_parsed_commands[COMMAND_COUNT];

/** Guard flag so Menu_Init runs exactly once. */
static int g_is_initialized = 0;

/* ---- internal helpers -------------------------------------------------- */

/**
 * @brief Case-insensitive ASCII string comparison (strcmp semantics).
 *
 * Lowercases each byte while scanning both strings in lockstep and returns
 * negative, zero, or positive to indicate ordering.
 *
 * @param a  Left-hand string.
 * @param b  Right-hand string.
 * @return 0 when strings are equal ignoring case.
 */
static int menu_stricmp(const char *a, const char *b)
{
    while (*a != '\0' && *b != '\0') {
        unsigned char ca = (unsigned char)tolower((unsigned char)*a);
        unsigned char cb = (unsigned char)tolower((unsigned char)*b);
        if (ca != cb) {
            return (int)ca - (int)cb;
        }
        ++a;
        ++b;
    }
    return (int)(unsigned char)tolower((unsigned char)*a)
         - (int)(unsigned char)tolower((unsigned char)*b);
}

/**
 * @brief Copies a bounded substring into fixed-size storage.
 *
 * Truncates when the source length exceeds the destination capacity and
 * always ensures NUL termination.
 *
 * @param dst       Destination buffer.
 * @param dst_size  Destination buffer size in bytes.
 * @param src       Source text pointer.
 * @param length    Number of bytes requested from source.
 */
static void menu_copy_token_text(char *dst, size_t dst_size,
                                 const char *src, size_t length)
{
    if (dst_size == 0u) {
        return;
    }
    if (length >= dst_size) {
        length = dst_size - 1u;
    }
    memcpy(dst, src, length);
    dst[length] = '\0';
}

/**
 * @brief Tokenizes a mutable string in-place using whitespace delimiters.
 *
 * Replaces delimiter bytes with NUL and stores pointers to each token
 * start into the caller-provided array.
 *
 * @param line        Mutable NUL-terminated input buffer.
 * @param tokens      Output array receiving token pointers.
 * @param max_tokens  Maximum number of token pointers to write.
 * @return Number of tokens found.
 */
static int menu_split_tokens(char *line, char *tokens[], int max_tokens)
{
    int   count = 0;
    char *p     = line;

    while (*p != '\0') {
        /* skip leading whitespace */
        while (*p != '\0' && isspace((unsigned char)*p)) {
            ++p;
        }
        if (*p == '\0') {
            break;
        }
        if (count >= max_tokens) {
            return count;
        }
        tokens[count++] = p;

        /* advance to next whitespace */
        while (*p != '\0' && !isspace((unsigned char)*p)) {
            ++p;
        }
        if (*p != '\0') {
            *p++ = '\0';
        }
    }
    return count;
}

/**
 * @brief Parses one command syntax string into runtime match metadata.
 *
 * Classifies each syntax token as keyword, required parameter, or optional
 * parameter and computes the minimum and maximum input-token counts used
 * for fast rejection during dispatch.
 *
 * Rules enforced:
 *  - Required parameters may not follow optional ones.
 *  - Keywords may not follow optional parameters.
 *
 * @param def  Command definition whose syntax field is parsed.
 * @param out  Output structure that receives parsed metadata.
 * @return 1 when the syntax is valid, 0 on rule violations.
 */
static int menu_parse_command_syntax(const MenuCommandDef *def,
                                     ParsedCommand *out)
{
    char  syntax_buffer[MENU_MAX_INPUT_LEN];
    char *tokens[MENU_MAX_TOKENS];
    int   token_count;
    int   i;
    int   optional_seen = 0;

    memset(out, 0, sizeof(*out));
    out->valid = 1;

    strncpy(syntax_buffer, def->syntax, sizeof(syntax_buffer) - 1u);
    syntax_buffer[sizeof(syntax_buffer) - 1u] = '\0';

    token_count      = menu_split_tokens(syntax_buffer, tokens, MENU_MAX_TOKENS);
    out->token_count = token_count;
    out->max_tokens  = token_count;

    for (i = 0; i < token_count; ++i) {
        const char  *t   = tokens[i];
        size_t       len = strlen(t);
        ParsedToken *pt  = &out->tokens[i];

        if (len >= 2u && t[0] == '[' && t[len - 1u] == ']') {
            /* required parameter */
            if (optional_seen) {
                out->valid = 0;
                break;
            }
            pt->type = MENU_TOKEN_REQUIRED_PARAM;
            menu_copy_token_text(pt->text, sizeof(pt->text), t + 1, len - 2u);
            ++out->min_tokens;
        } else if (len >= 2u && t[0] == '{' && t[len - 1u] == '}') {
            /* optional parameter */
            optional_seen = 1;
            pt->type = MENU_TOKEN_OPTIONAL_PARAM;
            menu_copy_token_text(pt->text, sizeof(pt->text), t + 1, len - 2u);
        } else {
            /* keyword */
            if (optional_seen) {
                out->valid = 0;
                break;
            }
            pt->type = MENU_TOKEN_KEYWORD;
            menu_copy_token_text(pt->text, sizeof(pt->text), t, len);
            ++out->min_tokens;
        }
    }

    return out->valid;
}

/**
 * @brief Attempts to match user input against one parsed command and dispatch.
 *
 * A command is marked "matched" only after ALL of the following succeed:
 *   1. Input token count is within [min_tokens, max_tokens].
 *   2. Every keyword token matches its position case-insensitively.
 *   3. Every required parameter is present.
 *   4. The callback pointer is non-NULL.
 *
 * The explicit @p matched output flag prevents false-positive dispatch
 * termination — the caller must check @c *matched, not the return code,
 * to decide whether the command was recognised.
 *
 * @param parsed       Pre-parsed command metadata.
 * @param def          Command definition (callback and help text).
 * @param input_count  Number of user-input tokens.
 * @param input_tokens Tokenized user input array.
 * @param matched      Output flag set to 1 only on a confirmed full match.
 * @return Callback return value on match; -1 when not matched or invalid.
 */
static int menu_match_and_dispatch(const ParsedCommand *parsed,
                                   const MenuCommandDef *def,
                                   int input_count,
                                   char *input_tokens[],
                                   int *matched)
{
    MenuCommandContext ctx;
    int i;
    int arg_index = 0;

    if (matched != NULL) {
        *matched = 0;
    }

    /* reject structurally invalid command definitions */
    if (!parsed->valid) {
        return -1;
    }

    /* fast rejection on token count */
    if (input_count < parsed->min_tokens || input_count > parsed->max_tokens) {
        return -1;
    }

    memset(&ctx, 0, sizeof(ctx));

    for (i = 0; i < parsed->token_count; ++i) {
        const ParsedToken *pt = &parsed->tokens[i];

        if (i >= input_count) {
            /* remaining tokens must all be optional */
            if (pt->type == MENU_TOKEN_OPTIONAL_PARAM) {
                continue;
            }
            return -1;
        }

        if (pt->type == MENU_TOKEN_KEYWORD) {
            if (menu_stricmp(pt->text, input_tokens[i]) != 0) {
                return -1;
            }
        } else {
            /* required or optional parameter — capture value */
            if (arg_index < MENU_MAX_ARGS) {
                ctx.argv[arg_index++] = input_tokens[i];
            } else {
                return -1;
            }
        }
    }

    ctx.argc = arg_index;

    if (def->callback == NULL) {
        return -1;
    }

    /* all checks passed — set match flag and invoke */
    if (matched != NULL) {
        *matched = 1;
    }

    return def->callback(&ctx);
}

/* ---- public API -------------------------------------------------------- */

/**
 * @brief Initializes parser metadata for every registered command entry.
 *
 * Pre-parses each syntax string and stores keyword/parameter metadata and
 * token-count bounds.  Must be called (or will be called lazily) before
 * the first call to Menu_ProcessLine().
 */
void Menu_Init(void)
{
    size_t i;

    for (i = 0; i < COMMAND_COUNT; ++i) {
        if (!menu_parse_command_syntax(&g_commands[i], &g_parsed_commands[i])) {
            fprintf(stderr, "Menu syntax error in command: %s\n",
                    g_commands[i].syntax);
            g_parsed_commands[i].valid = 0;
        }
    }
    g_is_initialized = 1;
}

/**
 * @brief Processes one input line and dispatches to the matching command.
 *
 * Workflow:
 *  1. Lazy-initializes metadata if Menu_Init() has not been called.
 *  2. Tokenizes the input line.
 *  3. Checks for built-in help aliases (HELP, ?) and EXIT/QUIT.
 *  4. Iterates the command table; stops ONLY when a command explicitly
 *     sets matched == 1.
 *  5. Prints an unknown-command error when no match is found.
 *
 * @param line  Raw NUL-terminated user input.
 * @return 0 on success/help/empty, callback rc on match, -1 on unknown.
 */
int Menu_ProcessLine(const char *line)
{
    size_t i;
    char   buffer[MENU_MAX_INPUT_LEN];
    char  *tokens[MENU_MAX_TOKENS];
    int    token_count;

    if (line == NULL) {
        return -1;
    }
    if (!g_is_initialized) {
        Menu_Init();
    }

    strncpy(buffer, line, sizeof(buffer) - 1u);
    buffer[sizeof(buffer) - 1u] = '\0';

    token_count = menu_split_tokens(buffer, tokens, MENU_MAX_TOKENS);
    if (token_count <= 0) {
        return 0;
    }

    /* built-in help aliases */
    if (menu_stricmp(tokens[0], "HELP") == 0
        || (token_count == 1 && strcmp(tokens[0], "?") == 0)) {
        Menu_PrintHelp();
        return 0;
    }

    /* dispatch loop — stop ONLY on explicit match */
    for (i = 0; i < COMMAND_COUNT; ++i) {
        int matched = 0;
        int rc = menu_match_and_dispatch(&g_parsed_commands[i],
                                         &g_commands[i],
                                         token_count,
                                         tokens,
                                         &matched);
        if (matched) {
            return rc;
        }
    }

    printf("ERR: Unknown command. Type HELP for available commands.\n");
    return -1;
}

/**
 * @brief Prints all registered commands with aligned syntax and description.
 *
 * Computes the maximum syntax-string width across every registered command
 * and the built-in aliases (HELP, ?, EXIT) so the " - " separator and
 * description text align on every line.
 */
void Menu_PrintHelp(void)
{
    size_t i;
    size_t max_syntax_width = 0u;
    int    width;

    const char *builtin_help       = "HELP";
    const char *builtin_help_alias = "?";
    const char *builtin_exit       = "EXIT";

    /* compute shared column width */
    for (i = 0; i < COMMAND_COUNT; ++i) {
        size_t len = strlen(g_commands[i].syntax);
        if (len > max_syntax_width) {
            max_syntax_width = len;
        }
    }
    if (strlen(builtin_help) > max_syntax_width) {
        max_syntax_width = strlen(builtin_help);
    }
    if (strlen(builtin_help_alias) > max_syntax_width) {
        max_syntax_width = strlen(builtin_help_alias);
    }
    if (strlen(builtin_exit) > max_syntax_width) {
        max_syntax_width = strlen(builtin_exit);
    }

    width = (max_syntax_width > (size_t)INT_MAX) ? INT_MAX
                                                  : (int)max_syntax_width;

    printf("Available commands:\n");
    for (i = 0; i < COMMAND_COUNT; ++i) {
        printf("  %-*s - %s\n", width,
               g_commands[i].syntax, g_commands[i].description);
    }
    printf("  %-*s - %s\n", width, builtin_help,       "Show this help");
    printf("  %-*s - %s\n", width, builtin_help_alias,  "Show this help");
    printf("  %-*s - %s\n", width, builtin_exit,        "Exit test harness");
}

/**
 * @brief Returns the internal command definition table and its count.
 *
 * @param count  If non-NULL, receives the number of table entries.
 * @return Pointer to the first element of the immutable command array.
 */
const MenuCommandDef *Menu_GetCommands(size_t *count)
{
    if (count != NULL) {
        *count = COMMAND_COUNT;
    }
    return g_commands;
}
