/*
 * Copyright (C) 2026 — Generated by MenuBuilder AI, inspired by Steve Spano
 *                        (SteveSpano009@gmail.com)
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 * USA
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

/**
 * @file  menu_callback_Test.c
 * @date  2026-02-27 12:00:00 -05:00
 * @brief Example callback implementations for the DAQ command set.
 *
 * Each callback prints its parsed arguments to stdout so the user can
 * verify that the parser extracted the correct tokens.  Replace these
 * stubs with real hardware-facing logic when integrating into a target.
 */

/*
 * ===========================================================================
 *  REVISION HISTORY
 * ===========================================================================
 *  Rev    Date        Author                          Description
 * ---------------------------------------------------------------------------
 *  1.0    2026-02-27  MenuBuilder AI / Steve Spano    Initial generation
 * ===========================================================================
 */

#include "menu.h"
#include <stdio.h>

/**
 * @brief Handles the DAQ INIT command.
 *
 * Prints the required RATE_HZ parameter and the optional CHANNEL_MASK
 * parameter if it was supplied by the user.
 *
 * @param ctx  Parsed argument context (argc 1–2).
 * @return 0 always (stub).
 */
int DaqInit(const MenuCommandContext *ctx)
{
    printf("[DaqInit] RATE_HZ=%s", ctx->argv[0]);
    if (ctx->argc > 1) {
        printf(", CHANNEL_MASK=%s", ctx->argv[1]);
    }
    printf("\n");
    return 0;
}

/**
 * @brief Handles the DAQ START command.
 *
 * Prints the optional DURATION_MS parameter if present, otherwise
 * indicates continuous acquisition mode.
 *
 * @param ctx  Parsed argument context (argc 0–1).
 * @return 0 always (stub).
 */
int DaqStart(const MenuCommandContext *ctx)
{
    if (ctx->argc > 0) {
        printf("[DaqStart] DURATION_MS=%s\n", ctx->argv[0]);
    } else {
        printf("[DaqStart] continuous mode\n");
    }
    return 0;
}

/**
 * @brief Handles the DAQ STOP command.
 *
 * No parameters.  Prints confirmation that acquisition has stopped.
 *
 * @param ctx  Parsed argument context (argc 0).
 * @return 0 always (stub).
 */
int DaqStop(const MenuCommandContext *ctx)
{
    (void)ctx;
    printf("[DaqStop] Acquisition stopped.\n");
    return 0;
}

/**
 * @brief Handles the DAQ READ command.
 *
 * Prints the required CHANNEL parameter so the caller can verify the
 * parser extracted the correct token.
 *
 * @param ctx  Parsed argument context (argc 1).
 * @return 0 always (stub).
 */
int DaqRead(const MenuCommandContext *ctx)
{
    printf("[DaqRead] CHANNEL=%s\n", ctx->argv[0]);
    return 0;
}

/**
 * @brief Handles the DAQ SET GAIN command.
 *
 * Prints both required parameters: CHANNEL and GAIN_DB.
 *
 * @param ctx  Parsed argument context (argc 2).
 * @return 0 always (stub).
 */
int DaqSetGain(const MenuCommandContext *ctx)
{
    printf("[DaqSetGain] CHANNEL=%s, GAIN_DB=%s\n",
           ctx->argv[0], ctx->argv[1]);
    return 0;
}

/**
 * @brief Handles the DAQ SET TRIGGER command.
 *
 * Prints the required SOURCE parameter and the optional LEVEL parameter
 * if it was supplied.
 *
 * @param ctx  Parsed argument context (argc 1–2).
 * @return 0 always (stub).
 */
int DaqSetTrigger(const MenuCommandContext *ctx)
{
    printf("[DaqSetTrigger] SOURCE=%s", ctx->argv[0]);
    if (ctx->argc > 1) {
        printf(", LEVEL=%s", ctx->argv[1]);
    }
    printf("\n");
    return 0;
}

/**
 * @brief Handles the DAQ STATUS command.
 *
 * Prints the optional DETAIL parameter if present, otherwise shows
 * a brief status summary.
 *
 * @param ctx  Parsed argument context (argc 0–1).
 * @return 0 always (stub).
 */
int DaqStatus(const MenuCommandContext *ctx)
{
    if (ctx->argc > 0) {
        printf("[DaqStatus] DETAIL=%s\n", ctx->argv[0]);
    } else {
        printf("[DaqStatus] OK\n");
    }
    return 0;
}

/**
 * @brief Handles the DAQ CALIBRATE command.
 *
 * Prints the required CHANNEL parameter and the optional REFERENCE_MV
 * parameter if it was supplied.
 *
 * @param ctx  Parsed argument context (argc 1–2).
 * @return 0 always (stub).
 */
int DaqCalibrate(const MenuCommandContext *ctx)
{
    printf("[DaqCalibrate] CHANNEL=%s", ctx->argv[0]);
    if (ctx->argc > 1) {
        printf(", REFERENCE_MV=%s", ctx->argv[1]);
    }
    printf("\n");
    return 0;
}

/**
 * @brief Handles the DAQ SAVE CONFIG command.
 *
 * Prints the required NAME parameter indicating which configuration
 * profile to save.
 *
 * @param ctx  Parsed argument context (argc 1).
 * @return 0 always (stub).
 */
int DaqSaveConfig(const MenuCommandContext *ctx)
{
    printf("[DaqSaveConfig] NAME=%s\n", ctx->argv[0]);
    return 0;
}

/**
 * @brief Handles the DAQ LOAD CONFIG command.
 *
 * Prints the required NAME parameter indicating which configuration
 * profile to load.
 *
 * @param ctx  Parsed argument context (argc 1).
 * @return 0 always (stub).
 */
int DaqLoadConfig(const MenuCommandContext *ctx)
{
    printf("[DaqLoadConfig] NAME=%s\n", ctx->argv[0]);
    return 0;
}
